title: Süleyman Poyraz
email: zaryob.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Kişisel olarak oluşturduğum kılavuz dosyalarını içeriyor
baseurl: "/kilavuzlar" # the subpath of your site, e.g. /blog
url: "zaryob.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pyrz_suleyman
github_username: Zaryob

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude: [vendor]

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
